language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 5.6
      env: DOCTRINE_VERSION=2.3.*
    - php: 5.6
      env: DOCTRINE_VERSION=2.4.*
    - php: 5.6
      env: DOCTRINE_VERSION=2.5.*

before_install:
  - composer selfupdate
  - if [ "$DOCTRINE_VERSION" != "" ]; then composer require "doctrine/orm:${DOCTRINE_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-clover=coverage.clover
